"""add prd_generation_jobs table

Revision ID: 03091b24ade6
Revises: ff7abcf307a7
Create Date: 2026-04-28 17:33:14.077978

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

import app.models._types  # noqa: F401  needed for TZDateTime references below
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "03091b24ade6"
down_revision: str | Sequence[str] | None = "ff7abcf307a7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "prd_generation_jobs",
        sa.Column("job_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("prd_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("project_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("total_chapters", sa.Integer(), nullable=False),
        sa.Column("completed_chapters", sa.Integer(), nullable=False),
        sa.Column("saved_cases", sa.Integer(), nullable=False),
        sa.Column("results", sa.JSON(), nullable=True),
        sa.Column("request_payload", sa.JSON(), nullable=True),
        sa.Column("error", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", app.models._types.TZDateTime(timezone=True), nullable=False),
        sa.Column("started_at", app.models._types.TZDateTime(timezone=True), nullable=True),
        sa.Column("finished_at", app.models._types.TZDateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("job_id"),
    )
    with op.batch_alter_table("prd_generation_jobs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_prd_generation_jobs_prd_id"), ["prd_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_prd_generation_jobs_project_id"), ["project_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("prd_generation_jobs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_prd_generation_jobs_project_id"))
        batch_op.drop_index(batch_op.f("ix_prd_generation_jobs_prd_id"))

    op.drop_table("prd_generation_jobs")
    # ### end Alembic commands ###
