"""initial schema

Revision ID: 748e2eb51696
Revises:
Create Date: 2026-04-27 17:57:28.063305

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "748e2eb51696"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "diagnoses",
        sa.Column("diag_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("run_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("case_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("diagnoser_prompt_version", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("diagnoser_model", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("category", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("reasoning", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("fix_suggestion", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("human_feedback", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("feedback_note", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("feedback_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("diag_id"),
    )
    with op.batch_alter_table("diagnoses", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_diagnoses_case_id"), ["case_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_diagnoses_run_id"), ["run_id"], unique=False)

    op.create_table(
        "patterns",
        sa.Column("pattern_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("pattern_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("matcher", sa.JSON(), nullable=True),
        sa.Column("suggested_action", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("hit_count", sa.Integer(), nullable=False),
        sa.Column("last_hit_at", sa.DateTime(), nullable=True),
        sa.Column("confirmed_by_diag_ids", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("pattern_id"),
    )
    op.create_table(
        "prds",
        sa.Column("prd_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("project_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("raw_markdown", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("content_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("chapters", sa.JSON(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("prev_version_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("uploaded_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("prd_id"),
    )
    with op.batch_alter_table("prds", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_prds_content_hash"), ["content_hash"], unique=False)
        batch_op.create_index(batch_op.f("ix_prds_project_id"), ["project_id"], unique=False)

    op.create_table(
        "projects",
        sa.Column("project_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("base_url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("default_username", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("default_password", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("project_id"),
    )
    op.create_table(
        "runs",
        sa.Column("run_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("trace_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("project_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("case_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("case_version", sa.Integer(), nullable=False),
        sa.Column("env", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("ended_at", sa.DateTime(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("artifacts_dir", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("report_html_path", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("trace_jsonl_path", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("error_message", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("run_id"),
    )
    with op.batch_alter_table("runs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_runs_case_id"), ["case_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_runs_project_id"), ["project_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_runs_trace_id"), ["trace_id"], unique=False)

    op.create_table(
        "step_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("step_index", sa.Integer(), nullable=False),
        sa.Column("event", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("intent", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("tool_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("tool_args", sa.JSON(), nullable=True),
        sa.Column("tool_result", sa.JSON(), nullable=True),
        sa.Column("screenshot_before", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("screenshot_after", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("error_message", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("occurred_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("step_events", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_step_events_run_id"), ["run_id"], unique=False)

    op.create_table(
        "test_cases",
        sa.Column("case_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("project_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("intent", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("module", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("tags", sa.JSON(), nullable=True),
        sa.Column("priority", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("preconditions", sa.JSON(), nullable=True),
        sa.Column("steps", sa.JSON(), nullable=True),
        sa.Column("assertions", sa.JSON(), nullable=True),
        sa.Column("source", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("prompt_version", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("model_version", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("generated_from", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("review_status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("manual_edited_fields", sa.JSON(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("prev_version_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("case_id"),
    )
    with op.batch_alter_table("test_cases", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_test_cases_project_id"), ["project_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("test_cases", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_test_cases_project_id"))

    op.drop_table("test_cases")
    with op.batch_alter_table("step_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_step_events_run_id"))

    op.drop_table("step_events")
    with op.batch_alter_table("runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_runs_trace_id"))
        batch_op.drop_index(batch_op.f("ix_runs_project_id"))
        batch_op.drop_index(batch_op.f("ix_runs_case_id"))

    op.drop_table("runs")
    op.drop_table("projects")
    with op.batch_alter_table("prds", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_prds_project_id"))
        batch_op.drop_index(batch_op.f("ix_prds_content_hash"))

    op.drop_table("prds")
    op.drop_table("patterns")
    with op.batch_alter_table("diagnoses", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_diagnoses_run_id"))
        batch_op.drop_index(batch_op.f("ix_diagnoses_case_id"))

    op.drop_table("diagnoses")
    # ### end Alembic commands ###
